language: scala

scala:
  - 2.10.6

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - |
    if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      if [ $RELEASE_ON_PUSH = 'false' ]; then
        sbt validate
      else
        sbt 'release with-defaults'
      fi
    else
      sbt validate
    fi
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

env:
  global:
    - secure: "Hkd3+lH/HjURLWpwONzCnWoyQaW+vYL5UUB0KPcypOpEJ8iIN0aFB8fc7C8lZVoQJEflHyaEv/i2fDTH3t4hrG4blvjwvuzbDy8UvmFK9qie1nQciCDzzxeO4adPVM2lOI1m/G+r5kSAu0X8/tlWWKJRJQTJPx/ReT27nHJK8FX2zTiObAzrSuR6kYSIRaVu5lOHCddmsKcZiW3A2nJeIDyaiTmDKQzrNI9SPAls/IlTBNf95LYmGTPj3Csdq8eFGDxZrj0rnZ0mg0uOh1lVZc4ODn11mUTVMI9iWICif+AehqMXcP2kyb3Sm6DjescqtGE6h8jtdJasyeIFexOgLSfn6LkL8hALII1WA7NRfJHm6Dw/wo4rVXmz4fMzdyC5FrV02GaT3O0gJsPB33wlPJn+WQsgDNkIfFJKU8/ArpaMbZzDTyKaBDchNpp2MfCY3d4n/OZneMrATwLCKC7spsqQdQ4eZt1OCSTgsESN3CqbFZlAzO8iMVl78rgOmAM4XETpGJUuFdZ7t3EBVhrG7uNjMLd/rqvmyzrsozOQwxDIXE7FxoA2L+WKUxMeFGL7lrGDzvqG04MPg4O7nWrezPcPdcYW3N6yI0OZEapidoZ9E/1cXwOQJQCu3kZDFAlZk5ifPcNj0gFklnnJ8faw/K8qm+6guUs5XEUz+gM/n9s="
    - secure: "ikRSgGPUS2h1qr599xOjwrACY7laW/0YHt2WHGF1tIziNGsXfm6+hKCpMbWAABi11V5uvm2J/yAbZY1RhHzeTvg3+1GWiIFc2VCBe6xE1FRE2TfVOYIUi0gLNzVkta35cA01FqzcN4iQE40WKcKD+6C0BZTAHIsY/ywMX0XNvwOCDDqfl3RlJvxNbkrqRkMDVbMEcc7unE5XTQWaUTxyiMB+em37iwqcdBmA8P1ijHV4pxH29Ic714MrLCX2l/iOLeJGa+iKWg6uc5qvMvV0Gcn9OhWhrlxAtFEoOm+qbqs0uvRP5LIvSSw7X5TISjz5s04DGLNrgyOTFyAFuAjaPdFXSJvgxnGasGgVL3JI3eXS2ABfzwJosh7Iy3kehzAc6wvq18iSE1Ed31y3UXQSzSQA36wLQVZNKEzgq76dsX1hrA28CmcfizcvcazXLcHYI3dHnqYmI+0Lw4qudveQ+Daso3fFjWMg7GpUbs61gFvYGoGs5sAxLCMeR7jYaucuffgdd+bXj9+nYTRFDhyerHGm9zJAp/q6Xobhfq4XRB6LxQnLmx2ieNBcerRQbSVg+pSVskG0XtJzOnR312+2md3La5IdQHJsn75OEnN6dCunDmmMzfM95m+lwVnT5TXpOHXdC0tCXcyiVDTjv66GCGkn9w0vZn7pzt2IPgBNv7I="
